# Generated by Django 5.2.7 on 2025-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_en', models.CharField(max_length=200, verbose_name='Degree (English)')),
                ('degree_fa', models.CharField(blank=True, max_length=200, verbose_name='Degree (Persian)')),
                ('university', models.CharField(max_length=200, verbose_name='University')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_fa', models.TextField(blank=True, verbose_name='Description (Persian)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_date', '-order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='Title (Persian)')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_fa', models.TextField(blank=True, verbose_name='Description (Persian)')),
                ('current', models.BooleanField(default=False, verbose_name='Current Position')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date', '-order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='Title (Persian)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_fa', models.TextField(blank=True, verbose_name='Description (Persian)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub Link')),
                ('demo_link', models.URLField(blank=True, verbose_name='Demo Link')),
                ('technologies', models.CharField(help_text='Comma-separated list', max_length=500, verbose_name='Technologies')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-featured', '-created_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools'), ('other', 'Other')], max_length=20, verbose_name='Category')),
                ('level', models.IntegerField(default=0, help_text='Percentage (0-100)', verbose_name='Level')),
                ('icon', models.CharField(blank=True, help_text='Icon class name (e.g., fa fa-html5)', max_length=100, verbose_name='Icon')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
