# Generated by Django 5.2.7 on 2025-11-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_fa', models.CharField(blank=True, max_length=200, verbose_name='Name (Persian)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profile Image')),
                ('title_en', models.CharField(default='Web Developer & Creative Problem Solver', max_length=200, verbose_name='Title (English)')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='Title (Persian)')),
                ('bio_short_en', models.TextField(blank=True, help_text='Brief introduction for hero section', verbose_name='Short Bio (English)')),
                ('bio_short_fa', models.TextField(blank=True, verbose_name='Short Bio (Persian)')),
                ('bio_long_en', models.TextField(blank=True, help_text='Detailed description for about page', verbose_name='Long Bio (English)')),
                ('bio_long_fa', models.TextField(blank=True, verbose_name='Long Bio (Persian)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X URL')),
                ('website_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('years_experience', models.IntegerField(default=0, verbose_name='Years of Experience')),
                ('projects_completed', models.IntegerField(default=0, verbose_name='Projects Completed')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
